#!/sbin/busybox sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ ! -z $3 ]]; then
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
fi

usb_mode_predef="0"
usb_mode_find=`grep "usb_mode_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

write_value() {  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  g_find=`grep $1=.* $DEFAULT_PROFILE`
    
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

case "$usb_modepredef" in
  0)
    /system/bin/setprop sys.usb.config mtp,adb;
    /system/bin/setprop persist.sys.usb.config mtp,adb;
    /system/bin/setprop sys.usb.state mtp,adb;
    usb_mode_predef="0"
    write_values
    ;;
  1)
    /system/bin/setprop sys.usb.config mass_storage,adb;
    /system/bin/setprop persist.sys.usb.config mass_storage,adb;
    /system/bin/setprop sys.usb.state mass_storage,adb;
    usb_mode_predef="1"
    write_values
    ;;
  *)
    if [[ ! -z $usb_mode_find ]]; then
      usb_mode_predef="$usb_mode_find"
    fi 
    ;;
esac;

eval echo $usb_mode_predef
